version: '2'
services:
    nginx:
        image: future2018/sanic_nginx:$IMAGE_TAG
        container_name: sanic_nginx_con
        ports:
            - "8888:80"
        links:
            - app
    app:
        image: future2018/sanic_url:$IMAGE_TAG
        container_name: sanic_url_con
        expose:
            - "8000"
        links:
            - postgres
        env_file:
            - ./.env
        depends_on:
            - postgres
    postgres:
        image: future2018/sanic_db:$IMAGE_TAG
        container_name: sanic_db_con
        env_file:
            - ./.env
        volumes:
            - ./pg:/var/lib/postgres/data/
        expose:
            - "5432"
